baseURL: 'https://hilderogge.be/'
title: Hilde Rogge
languageCode: nl
theme: hilde
author:
  hilde: Hilde Rogge

params:
  title: Hilde Rogge
  description: "Hilde Rogge is een verhalenvertelster pur sang."
  site_description: "Hilde Rogge is een verhalenvertelster pur sang."
  locale: nl-BE
  images:
    - "https://hilderogge.be/img/home-hero.jpg"
  telephone: "+32495407025"
  email: "hilde.rogge@outlook.com"
  copyright: 'Copyright &copy; Hilde Rogge'
  developer: "Ontwikkeld door [Marcel Samyn](https://samyn.co)"

social:
  facebook: "hilde.rogge.5"

menu:
  main:
    - identifier: home
      name: Hilde Rogge
      title: Hilde Rogge
      url: /
      weight: 1
    - identifier: bio
      name: Bio
      title: Bio
      url: /bio/
      weight: 2
    - identifier: vertelsels
      name: Vertelsels
      title: Vertelsels
      url: /vertelsels/
      weight: 3
    - identifier: expedities
      name: Expedities
      title: Expedities
      url: /expedities/
      weight: 4
    - identifier: digitalalal
      name: Digitalalala
      title: Digitalalala
      url: /digitalalala/
      weight: 5
    - identifier: fotos
      name: Foto's
      title: Foto's
      url: /fotos/
      weight: 6
    - identifier: contact
      name: Contact
      title: Contact
      url: /contact/
      weight: 7

enableRobotsTXT: true
canonifyURLs: true
