[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.80.0"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
