backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Add rating/reviewing workflow
publish_mode: editorial_workflow

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "vertelsels" # Used in routes, e.g., /admin/collections/blog
  label: "Vertelsels" # Used in the UI
  folder: "content/vertelsels" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Titel", name: "title", widget: "string"}
    - {label: "Samenvatting", name: "summary", widget: "string"}
    - {label: "Datum", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
- name: "expedities" # Used in routes, e.g., /admin/collections/blog
  label: "Expedities" # Used in the UI
  folder: "content/expedities" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Titel", name: "title", widget: "string"}
    - {label: "Samenvatting", name: "summary", widget: "string"}
    - {label: "Datum", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
- name: "digitalalala" # Used in routes, e.g., /admin/collections/blog
  label: "Digitalalala" # Used in the UI
  folder: "content/digitalalala" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Titel", name: "title", widget: "string"}
    - {label: "Samenvatting", name: "summary", widget: "string"}
    - {label: "Datum", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
